### PR TITLE
Disable coq-native in Coq 8.13+

### PR DESCRIPTION
**Pull request by erikmd**
as decided in the Zulip thread (steps 1 and 2 of [this wrap-up](https://coq.zulipchat.com/#narrow/stream/237656-Coq-devs.20.26.20plugin.20devs/topic/recent.20changes.20to.20the.20native.20compiler.3F/near/219483880)) (Cc @gares @Zimmi48 @ejgallego @palmskog FYI)

### CODE REVIEW

**Comment by Zimmi48** [comment]
I haven't read the whole Zulip thread yet, but it seems that @Blaisorblade was saying that native + flambda is problematic, so why not put a non-flambda compiler for the `coq-native` Docker image?

**Comment by erikmd** [comment]
Hi @Zimmi48, I didn't do it yet as:
* the issue with flambda mentioned by Paolo was especially for macOS,
* and even if Paolo noticed a slowdown for Linux: he had only benched the "precompilation" time, not the `native_compute` running time (which could be improved BTW(?), so ideally as I had mentioned in the thread, we'd need to do a bit more benchmarks),
* also when discussing with @ejgallego in thread, the final suggestion was to mark the `coq-native` package `conflicts:` with "(ocaml < 4.07) + flambda", not for any flambda variant;
* and finally the current change was more straightfoward to implement in docker-coq + docker-coq-action (but what you suggest in your comment can be done just as well of course!)

**Comment by ejgallego** [comment]
@Zimmi48 native + flambda is in principle fine, however you pay a bit more of overhead in native compilation due to the OCaml compiler being slower; the rest should work fine if the user wants both, modulo the usual problems w.r.t. OCaml compiler and large files.

**Comment by ejgallego** [comment]
Note that the conflict of native with < 4.07.0 is just due to flambda taking quite unreasonable memory demands before, but it still works, but a couple of files in the stdlib require 10 GiB of RAM to compile.

**Comment by Zimmi48** [comment]
The Docker image main use case is to check compatibility in CI, not to reap the benefits later on. It seems that users wanting to check compatibility with native-compute would benefit from shorter build times and those would be brought by a non-flambda compiler in the majority of cases.

**Comment by erikmd** [comment]
OK thanks @Zimmi48 @ejgallego! let's do that. Fortunately the new setup had not been announced yet. I'll open two PRs just now.

**Comment by erikmd** [comment]
BTW @Zimmi48 regarding [the "backward compatibility"](https://coq.zulipchat.com/#narrow/stream/237656-Coq-devs.20.26.20plugin.20devs/topic/recent.20changes.20to.20the.20native.20compiler.3F/near/219471209) concern you had raised, is [the plan I recapped](https://coq.zulipchat.com/#narrow/stream/237656-Coq-devs.20.26.20plugin.20devs/topic/recent.20changes.20to.20the.20native.20compiler.3F/near/219483880) OK for you?

Namely, removing the coq-native package from Coq < 8.13 as well (in a similar way as this PR) but just in one week after the upcoming announce?

**Comment by Zimmi48** [comment]
No, I think it is more reasonable to have `coq-native` installed in earlier images. I think that the other participants to the discussion didn't really understand the consequences. It would probably deserve a separate debate...

**Comment by erikmd** [comment]
@Zimmi48 OK, given the "coqc propagation" does not impact earlier images. The only impact could be related to item 3 (but for "selected libraries").

> It would probably deserve a separate debate..

OK but whatever is the strategy chosen, we'll need to announce it soon…
do you believe we should follow-up in Zulip now (maybe in another stream) to summarize this latter point?
Unfortunately I'm very busy this afternoon so I can't commit to discuss much

**Comment by Zimmi48** [comment]
I was also too busy to follow up and I've not liked the tone of this Zulip thread at all, so I'm wary of starting a new discussion on Zulip. Can it wait for the next Coq Call? Or is it too problematic to lengthen the transition period because of this?

**Comment by erikmd** [comment]
Hi @Zimmi48, thanks for your message.

> Can it wait for the next Coq Call?

Yes, if you refer to next Wednesday's Coq call (2020-12-16) I guess that's OK to wait until then!

**Comment by Zimmi48** [comment]
OK, can you add this to the list of topics to be discussed?

**Comment by erikmd** [comment]
@Zimmi48 done: https://github.com/coq/coq/wiki/Coq-Call-2020-12-16

**Pull request merged**
