### PR TITLE
feat: Adapt to https://github.com/coq/coq/pull/15560

### PR DESCRIPTION
**Pull request by erikmd**
Follow-up of [this discussion on Zulip](https://coq.zulipchat.com/#narrow/stream/237656-Coq-devs-.26-plugin-devs/topic/Big.20Dune.20PR.20incoming/near/287350919)

Cc @ejgallego

### CODE REVIEW

**Comment by ejgallego** [comment]
Thanks a lot @erikmd , it looks great . Note that version tho will only work for dev and 8.17 upwards, but I guess that's taken into account.

**Comment by Alizter** [comment]
@erikmd I will merge https://github.com/coq/coq/pull/15560 on Monday at the earliest.

**Comment by erikmd** [comment]
OK thanks @Alizter !

In the meantime, one can do the following just FYI:

* `docker run --rm -it coqorg/coq:newdev-4.14-flambda`
* `docker run --rm -it coqorg/coq:newdev`
* `docker run --rm -it coqorg/coq:newdev-4.12-flambda`
* `docker run --rm -it coqorg/coq:newdev-4.09-flambda`
* `docker run --rm -it coqorg/coq:newdev-native`

**Comment by Alizter** [comment]
@erikmd Please merge and then I will merge the consolidation PR shortly afterwards.

**Comment by erikmd** [comment]
@Alizter merged, but we now need to wait for 5' because of https://github.com/coq/bot/issues/234

**Comment by Alizter** [comment]
Will merge when CI green

**Comment by erikmd** [comment]
> so I'll let you know when it's OK

OK now! so you can merge the dune PR when you see fit.

**Pull request merged**
